# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-07-13 10:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DocExplainerBlock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_id', models.CharField(max_length=255)),
                ('text', models.TextField()),
                ('xml_text', models.TextField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'web_docexplainerblock',
                'verbose_name': 'Law Explainer',
                'verbose_name_plural': 'Law Explainers',
            },
        ),
        migrations.CreateModel(
            name='WebDoc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frbr_url', models.TextField()),
                ('document_id', models.IntegerField(db_index=True)),
                ('short_title', models.TextField()),
                ('long_title', models.TextField(blank=True)),
                ('number', models.IntegerField(null=True)),
                ('date', models.DateField(null=True)),
                ('year', models.IntegerField(null=True)),
                ('subtype', models.CharField(blank=True, max_length=255)),
                ('locality', models.CharField(blank=True, max_length=255)),
                ('locality_id', models.IntegerField(null=True)),
                ('category', models.CharField(blank=True, max_length=255)),
                ('category_id', models.IntegerField(null=True)),
                ('tags', models.TextField(blank=True)),
                ('document_created_at', models.DateTimeField(null=True)),
                ('document_updated_at', models.DateTimeField(null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('is_draft', models.BooleanField(default=True)),
                ('is_stub', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'web_webdoc',
                'verbose_name': 'Law Document',
                'verbose_name_plural': 'Law Documents',
            },
        ),
        migrations.CreateModel(
            name='WebDocXmlData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('xml_data', models.TextField(blank=True)),
                ('nyaaya_xml_data', models.TextField(blank=True)),
                ('toc_json', models.TextField(blank=True)),
                ('webdoc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='xmldata', to='law.WebDoc')),
            ],
            options={
                'db_table': 'web_webdocxmldata',
                'verbose_name': 'Law XML Data',
                'verbose_name_plural': 'Law XML Data',
            },
        ),
        migrations.AddField(
            model_name='docexplainerblock',
            name='webdoc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='explainer', to='law.WebDoc'),
        ),
    ]
