# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-07-13 10:01
from __future__ import unicode_literals

from django.db import migrations, models
import seo.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StaticSeo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.TextField(max_length=255, unique=True)),
                ('title', models.CharField(max_length=70)),
                ('meta_description', models.TextField(max_length=160)),
                ('h1', models.CharField(blank=True, max_length=70)),
                ('lang', models.CharField(default='en', max_length=8)),
                ('og_type', models.CharField(blank=True, max_length=20)),
                ('og_title', models.CharField(blank=True, max_length=70)),
                ('og_description', models.TextField(blank=True, max_length=160)),
                ('og_image', models.ImageField(blank=True, upload_to=seo.models.upload_to_seo_static)),
                ('og_author', models.TextField(blank=True, max_length=255)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'seo_staticseo',
                'verbose_name': 'SEO/Social Tags for Static Url',
                'verbose_name_plural': 'SEO/Social Tags for Static Urls',
            },
        ),
    ]
