# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-07-13 10:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields
import pyramid.models
import stdimage.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppTOC',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=225)),
                ('slug', models.SlugField(blank=True, max_length=225, null=True)),
                ('illustration', stdimage.models.StdImageField(blank=True, null=True, upload_to=pyramid.models.upload_to_toc_illustrations)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lft', models.PositiveIntegerField(db_index=True, editable=False)),
                ('rght', models.PositiveIntegerField(db_index=True, editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(db_index=True, editable=False)),
            ],
            options={
                'db_table': 'pyramid_apptoc',
                'verbose_name': 'Table of Content',
                'verbose_name_plural': 'Table of Contents',
            },
        ),
        migrations.CreateModel(
            name='NyaayaApp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=225)),
                ('theme', models.CharField(choices=[('DN', 'Explainers : Dummy-parent Doc without right Nav'), ('DU', '---- : Dummy-parent Doc without Nav'), ('BL', 'Blog : Theme with published date'), ('ST', 'Static : Theme for static pages'), ('AA', 'Guides : Default Theme for Readbility')], db_index=True, default='AA', max_length=2)),
                ('lang', models.CharField(choices=[('EN', 'English'), ('HIN', 'Hindi')], default='EN', max_length=5)),
                ('illustration', stdimage.models.StdImageField(blank=True, null=True, upload_to=pyramid.models.upload_to_config_illustrations)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'pyramid_nyaayaapp',
                'verbose_name': 'App Config',
                'verbose_name_plural': 'App Configs',
            },
        ),
        migrations.CreateModel(
            name='PyramidDoc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('raw_content_state', models.TextField(blank=True)),
                ('plain_text', models.TextField(blank=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('is_draft', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('published_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'pyramid_pyramiddoc',
                'verbose_name': 'Article',
                'verbose_name_plural': 'Articles',
                'permissions': (('can_publish', 'Can publish articles'),),
            },
        ),
        migrations.AddField(
            model_name='apptoc',
            name='app',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tocs', to='pyramid.NyaayaApp'),
        ),
        migrations.AddField(
            model_name='apptoc',
            name='parent',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='pyramid.AppTOC'),
        ),
        migrations.AddField(
            model_name='apptoc',
            name='pyramid_doc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pyramid.PyramidDoc'),
        ),
    ]
